### ISSUE TITLE
Keep getting error attempted import error

### ISSUE THREAD

**Issue by samrith-s** [jacobwgillespie/styled-icons#1147] opened 2020-02-05 20:14 UTC
Hey,

We are using `v9.2.0` in our CRA app. We periodically run into a `Attempted import error: <icon-name> is not exported from styled-icons/boxicons-solid/<icon-name>`. 

No idea how to solve this, and am unable to pinpoint what’s causing it, as everyone in the team isn’t able to consistently replicate it. 

Any help is appreciated!

**Comment by jacobwgillespie** [comment] 2020-02-05 20:49
Hey, thanks for raising this issue - if you are able to provide code that reproduces this issue I'd be happy to take a look.  I haven't seen this before, and from the error message it looks like it's trying to dynamically require an icon, but with the icon name being an empty string `""`, but I'm unfamiliar with what would cause that.  

My best shot-in-the-dark guess would be you have a dynamic `import` in a component somewhere and there's a brief moment where the icon name prop or state value is briefly empty on mount.  But that's just a wild guess, I'd be happy to take a look if you're able to create a reproduction.

**Comment by samrith-s** [comment] 2020-02-06 05:28
Hey,

I’ll try to reproduce it. 

But for example the LockAlt icon, we get: 
ˋAttempted import error: LockAlt is not exported from styled-icons/boxicons-solid/LockAltˋ.

**Comment by anasbud** [comment] 2020-02-18 11:13
Same here. 

`Cannot find module '@styled-icons/material/KeyboardArrowRight' from 'KeyboardArrowRight.js'`

**Comment by jacobwgillespie** [comment] 2020-02-19 00:27
@anasbud can you provide an example repo that shows the issue?  No worries either way, but if I have an example I can test locally it makes it quite a bit faster to debug.

**Comment by anasbud** [comment] 2020-02-19 07:07
I'm sorry, company private repo.

` Cannot find module 'styled-icons/fa-solid/Check' from 'CheckBox.js'

    However, Jest was able to find:
    	'../shared/CheckBox.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['ts', 'tsx', 'js', 'jsx'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      2 | import React from 'react';
      3 | import styled from 'styled-components';
    > 4 | import { Check } from 'styled-icons/fa-solid/Check';
        | ^
`

But Jenkins pipeline keeps failing when running tests.

**Comment by StevenLangbroek** [comment] 2020-02-26 21:20
Hey @jacobwgillespie! We're having this issue as well in https://github.com/styled-components/styled-components-website/pull/604. You should be able to see the results in Travis, none of us can reproduce it locally though weirdly enough. I tried changing the imports from `'styled-icons/fa-brands/[name]` instead of from `styled-icons/fa-brand`, but that didn't help either.

I'll need some time to dig into this repo setup if you'd like some help. Realistically speaking, that would be early / mid next week. Let me know if that's ok for you :).

**Comment by jacobwgillespie** [comment] 2020-02-26 22:32
@StevenLangbroek thanks for the link, I can check out the `styled-components-website` repo/build as well 🙏

**Comment by jacobwgillespie** [comment] 2020-02-29 11:18
@samrith-s and @anasbud, can you try switching to the individual icon pack packages?  You'd replace `styled-icons/fa-solid/Check` with `@styled-icons/fa-solid/Check` and install `@styled-icons/fa-solid`?  I think the issue may relate to problems unpacking all the files in the very large `styled-icons` package.

**Comment by anasbud** [comment] 2020-02-29 11:28
Yes that's what we finally end up doing. I fixed the issue but i'm still wondering what was the problem?

**Comment by jacobwgillespie** [comment] 2020-02-29 11:36
Cool, so there are a _lot_ of files in the `styled-icons` package, by guess is that sometimes it has trouble extracting all of them.  I would expect slower disks or slower CPUs (like on CI) to encounter that issue more frequently, which seems to be the case.

Styled Icons v10 is actually going to drop the `styled-icons/PACK/ICON` exports (`@styled-icons/PACK/ICON` will still work) as we've hit a file count limit and can't publish a module with that many files to NPM 😛

**Comment by jacobwgillespie** [comment] 2020-03-04 00:31
As `styled-icons` v10 has been released, I'm closing this issue, but feel free to post back if you encounter this issue again after upgrading.

**Closed by jacobwgillespie** 2020-03-04 00:31 UTC
