### ISSUE TITLE
Module not found: Can't resolve '@styled-icons/feather/FolderPlus'

### ISSUE THREAD

**Issue by farshed** [jacobwgillespie/styled-icons#1191] opened 2020-03-09 09:20 UTC
I've been experiencing this issue after I upgraded from v9.3.0 to v10.2.1. This error is thrown randomly for icon imports throughout the app. Sometimes the build compiles successfully and then after a few reloads, it fails with this error.

React v16.12.0
Electron v8.0.0

**Comment by jacobwgillespie** [comment] 2020-03-13 10:15
Hey @farshed can you provide any more details about your setup?  Operating system, what bundler you're using, etc.  If you can provide a repository example that reproduces the issue that would be awesome.

It looks like the same thing as #1147 - previously I had assumed that it was due to the number of files on disk, but it may have another root cause.

**Comment by farshed** [comment] 2020-03-13 17:15
@jacobwgillespie It seems that when you install the package it creates two folders in the node-modules directory; `styled-icons` & `@styled-icons`.
So before updating the package, I was importing the icons from `styled-icons` and it was working fine but after the update, all those imports randomly stopped working. I checked the folder and some of the icons inside it were missing. So I changed the imports to `@styled-icons`, rebuilt the project and everything started working again.

Btw, I'm using the default create-react-app bundler (webpack) on macOS.

**Comment by stramel** [comment] 2020-03-13 17:35
@farshed `v10` had breaking changes for icon imports from `styled-icons`. This was documented in the changelog. https://github.com/jacobwgillespie/styled-icons/blob/master/CHANGELOG.md#v1000---2020-03-03

Closing this as it is intended functionality

**Closed by stramel** 2020-03-13 17:35 UTC
