### ISSUE TITLE
Problem using named imports (fa-solid)

### ISSUE THREAD

**Issue by iliyanyotov** [jacobwgillespie/styled-icons#531] opened 2019-01-16 14:16 UTC
**Describe the bug**
The error is being shown when bundling the app and using the example import shown below:

`import { User, SignOutAlt, AngleDown } from 'styled-icons/fa-solid';`

[Image of the error](https://imgur.com/9kLHkSt)
[tsconfig.json](https://gist.github.com/iliyanyotov/7d74fdb63194dfa8e521abaa58742101)

Using the `.cjs` imports work fine but we are dragging a lot of unused icons (all icons from fa-solid) and that's not the desired solution:

`import { User, SignOutAlt, AngleDown } from 'styled-icons/fa-solid/index.cjs.js';`

Updating the library version to the latest one didn't fix the issue.

**Expected behaviour**
Bundle only the imported icons without any errors.

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2018
- Typescript: `"typescript": "^3.1.1",`
 - Version: `"styled-icons": "5.1.0",`

**Comment by iliyanyotov** [comment] 2019-01-21 11:43
We are using `webpack` with `babel-loader`, transpiling React and Typescript using respectively `@babel/preset-react` and `@babel/preset-typescript`.

Versions:
> "webpack": "^4.28.3",
> "babel-loader": "^8.0.5",
> "@babel/preset-react": "^7.0.0",
> "@babel/preset-typescript": "^7.1.0",

Babel configuration: [.babelrc](https://gist.github.com/iliyanyotov/4e7622898051239687fe349981138393)

**Comment by jacobwgillespie** [comment] 2019-01-21 13:58
Hey, thanks for the extra detail - Webpack 4 should be supported here.  Can you share your Webpack config?  That should show exactly what Webpack would do with a file inside `node_modules`.

**Comment by iliyanyotov** [comment] 2019-01-23 11:31
The webpack config is deconstructed across multiple files so it's reusable for the different parts of our app, but most of the stuff are pretty standard. I think the biggest configuration is within the `.babelrc` and the `tsconfig.json `files.

[babel loader](https://gist.github.com/iliyanyotov/4410fdac81ea76628cd79a349f07a27a)


Let me know if you want anything more specific.

**Comment by jacobwgillespie** [comment] 2019-01-23 15:22
Thanks for the additional details - one more question, do you have a server-side render or a prerender component to your app?  I'm just now noticing that the original error is a Node stacktrace, not a Webpack error.

If you do have something running in on the server, can you describe how that's built and run?

**Comment by jacobwgillespie** [comment] 2019-01-24 16:35
Cool, I think I have an idea of what's going on. I'll assume that you also use Webpack on the server-side to pre-process the JavaScript, but see below if not.

When your Webpack config builds the JavaScript for the client-side bundle, it packages your application code as well as all your dependencies into the resulting JavaScript files - therefore `styled-icons` source code is also included in the bundle.  As a result, Webpack performs tree shaking and then converts the `import`/`export` statements into Webpack requires.  And everything works.

When Webpack builds your server JavaScript, it packages all your application code into the final bundle, but it leaves out all your dependencies, since in a Node environment those dependencies are still available with `require(...)`.  That works okay for most things, but in this case the `styled-icons` source still contains those `import`/`export` statements, which Node does not understand, and that's what's giving you the error.

The fix is that Webpack needs to be configured so that the `externals` excludes the `styled-icons` package, even though it's a child of `node_modules`, so that it's processed by Webpack and included in the bundle.

This is how `next-plugin-styled-icons` does that - it's taking an existing `config.externals` and modifying it to exclude `styled-icons` from the externals list:

https://github.com/jacobwgillespie/styled-icons/blob/86b575e5dda18ae70c2e58673d215cfbba918a35/packages/next-plugin-styled-icons/index.js#L6-L14

If you happen to be using `webpack-node-externals`, then it has a `whitelist` option you can use:

```typescript
const nodeExternals = require('webpack-node-externals')

const config = {
  ...
  externals: [
    nodeExternals({
      whitelist: [/^styled-icons/],
    })
  ],
  ...
}
```

This is all very similar to `lodash-es`, if you've ever configured Webpack to work with that module.

If you're not using Webpack to bundle the server side code, you might consider using a bundler for this exact case here - Webpack, Rollup, Microbundle, `@zeit/ncc`, etc. should all work with Styled Icons.

**Comment by iliyanyotov** [comment] 2019-01-25 10:42
First of all, thanks for the extensive response and help with the issue!

Yes, we are using `webpack-node-externals` and it works flawlessly after the library is added to the whitelist property in Webpack.

The only problem left with the imports is now happening in the tests with `Jest`, and I think we need to configure `transformIgnorePatterns` to include `styled-icons`, but that didn't work.

[Image of the error](https://imgur.com/6qZaYpx)

`transformIgnorePatterns: ['node_modules/(?!(styled-icons)/)']`

**Comment by jacobwgillespie** [comment] 2019-01-25 15:03
Nice, glad to hear it's working!

This is what I have for Jest - I think the difference is I'm matching the entire file path, so maybe that's what makes the difference?

```json
"transformIgnorePatterns": ["node_modules/(?!(styled-icons)).+\\.(js|jsx|mjs)$"],
```

**Comment by iliyanyotov** [comment] 2019-02-06 10:21
Sorry for the delayed response, but this pattern didn't work, maybe we have something specific in our jest config. 

Will upload the config we are using later today. Thanks!

**Comment by Roman971** [comment] 2019-02-10 02:32
My Jest tests have exactly the same type of errors when using the non `.cjs` imports. 
When it comes to the config I'm only using the base create-react-app config. I also tested it on a fresh create-react-app project and doing any non `.cjs` styled-icons import broke tests. I also tried using `transformIgnorePatterns` but it didn't help either.

Everything works fine when using the `.cjs` versions so it's what I'm using for now but as stated previously this isn't ideal.

**Comment by jacobwgillespie** [comment] 2019-02-10 03:29
@Roman971 would you be able to provide the entirety of your `jest` config from `package.json` (or even better, the whole `package.json` with Jest config and dependencies)?  I'd be happy to take a look if I can get a reproducible example.

**Comment by Roman971** [comment] 2019-02-10 13:51
I don't have an actual Jest config since I'm using create-react-app.

If you want to reproduce it, those are the steps I did that lead me to broken tests:

- create a fresh project with `npx create-react-app test-styled-icons`
- install `styled-components` and `styled-icons` with `npm i styled-components styled-icons`
- add any styled-icons import to `App.js`, for instance `import { Github } from 'styled-icons/fa-brands'`
- run tests with `npm test`

Note that everything works fine when running/building the app with `npm start` and `npm run build`, the only issues appear when running tests with Jest.

**Comment by jacobwgillespie** [comment] 2019-02-12 04:58
Ah, I see what's going on, and it looks like Jest running inside `create-react-app` actually won't let you customize the `transformIgnorePatterns` since it's not in the list of approved Jest config overrides.

I believe I found a workaround that's even better, where any of the `styled-icons` imports automatically work with both CommonJS for Node / Jest / Next.js server and with ESM for Webpack, Rollup, etc and tree shaking.

I just released this as `styled-icons` v7.0.0 - @iliyanyotov and @Roman971 can you give that version a try?  If you have any `.cjs` imports, you'll want to remove the `.cjs` suffix, but after that everything should just work.

**Comment by Roman971** [comment] 2019-02-12 08:25
Thanks, it works fine on my end now after updating to v7.0.0 and changing the imports.

**Comment by jacobwgillespie** [comment] 2019-02-13 05:51
I'm going to close this as I believe this should now be fully resolved, but @iliyanyotov if anything's still broken, let me know and I'll re-open.  You will want to:

1. Upgrade to v7.0.0+
1. Remove any `.cjs` imports
1. Remove `styled-icons` from `webpack-node-externals` config (no longer necessary)
1. Remove `styled-icons` from `transformIgnorePatterns` (no longer necessary)

Basically after v7.0.0, all the `styled-icons/*` imports should just work like any other NPM module in the browser, Node, or Jest without any special config.

**Closed by jacobwgillespie** 2019-02-13 05:51 UTC
