### ISSUE TITLE
Empty svg being rendered

### ISSUE THREAD

**Issue by babycourageous** [jacobwgillespie/styled-icons#415] opened 2018-11-15 16:20 UTC
I'm sure I'm just missing something glaringly obvious but currently my usage of styled-icons is rendering an empty svg element. 
`<svg class="sc-fQejPQ jDkHNW"></svg>`
I'm just using the example shown on the README section. Any thoughts?

Thanks!
Looking forward to getting some styled icons in my project!

**Comment by jacobwgillespie** [comment] 2018-11-15 22:42
Which example are you trying?  I did just discover a typo on the README (`<Account />` should be `<AccountCircle />`) but it seems to be otherwise functional for me:

https://codesandbox.io/s/3qn896112p

If you have any other details I'd be happy to take a look!

**Comment by babycourageous** [comment] 2018-11-15 23:45
Crazy - that's basically identical to what I've got - import named icon from package and use it in component but it renders an empty svg element. The only difference I can tell is that I have react-scripts 2.0.5 and that codesandbox is 2.0.3

bizarre.
Oh - good catch on that typo - was about to let ya know about it!

**Comment by jacobwgillespie** [comment] 2018-11-16 00:06
Would you be able to create a simple repo to reproduce?  I’d be happy to debug.

**Comment by babycourageous** [comment] 2018-11-16 00:12
Yeah - I'll try to throw a simple project up!

**Comment by VictorGiroud** [comment] 2018-11-16 12:29
If it can help you:
I had the same issue with styled-components@4.0.3.
Updated in 4.1.1 after looking at peerDepencies ("styled-components": "> = 4.1.0 <5") and it worked.

**Comment by jacobwgillespie** [comment] 2018-11-16 15:15
Ah yes, that would cause this issue.  Yep the breaking change in `styled-icons v4 was requiring at least `styled-components v4.1 or newer.  Nice catch.

**Comment by babycourageous** [comment] 2018-11-16 15:42
Oh great! Thanks - they must have updated recently. I made that change and it's no longer empty. Thanks for the assist!

**Comment by jacobwgillespie** [comment] 2018-11-16 19:39
I'm going to close this issue since we've figured out the culprit - feel free to post back or open a new issue if anything else arises!

**Closed by jacobwgillespie** 2018-11-16 19:39 UTC
