### ISSUE TITLE
Cross-browser compatibility: Font-Awesome icons are not visible in Firefox

### ISSUE THREAD

**Issue by Andruschenko** [jacobwgillespie/styled-icons#432] opened 2018-11-27 23:02 UTC
I used the newest version **v5.1.0** with font awesome icons.

Problem: The icons are visible in **Chrome** but not in **Firefox (63.0.3)**.

### How to reproduce:

1. Begin project with create-react-app
2. Add styled-icons **v5.1.0** to project
3. Use any font-awesome icon

**Comment by jacobwgillespie** [comment] 2018-11-27 23:11
@Andruschenko what version of `styled-components` do you have installed?

I created this CodeSandbox using `styled-icons` v5.1.0, and I am able to see the icon in Firefox 63.0.3: https://codesandbox.io/s/n0pjv37o4l.

Do you have a repo or CodeSandbox or similar that shows this issue?  I'd be happy to dig further to see what's going on.

**Comment by Andruschenko** [comment] 2018-11-27 23:37
`styled-components` version is `4.1.1`. Because of this issue I unfortunately moved on to use the `react-icons` library.

I checked an it doesn't work for me in Firefox with the versions `"styled-components": "^3.3.0"` and `"styled-icons": "^2.2.0"` in a former project.

I tried to recreate the error but in this CodeSandbox it is visible but in my project it still is not.

**Comment by jacobwgillespie** [comment] 2018-11-28 00:11
Gotcha - yeah there's an issue where if you're using Styled Icons >5 and Styled Components <4.1, the icons don't display.

I think I found the issue!  Here's the repo I'm using: https://github.com/jacobwgillespie/ff-styled-icons-reproduction.

The issue isn't `styled-icons`, the issue is the CSS in your `Element` link interacting with a Firefox bug.  

You've set the width of the styled anchor element `<Element>` to be 2em, but then you applied a padding to the inner `<svg>` of `0 3em`.  That means the top and bottom padding are 0 (which is fine), but critically the left padding is 3em.  That shifts the icon to the right by 3em, which is outside the width of its parent `<a>`.

When that happens in Chrome, it just shifts to the right.  When it happens in Firefox though, it shifts to the right **and** its height becomes 0.  If you do actually want the 2em/3em values, you can preserve the height by modifying your CSS:

```css
> svg {
  padding: 0 3em;
  height: 1em;
}
```

Or maybe you wanted something different and this workaround wouldn't be necessary.

Anyways, I don't think this has anything to do with FontAwesome, as the same issue occurs for me with any of the other icons.  I also think this is a bug on Firefox's part - I wasn't able to find a specific bug report that seemed to exactly match this case, but there are lots of bug reports about 0-height SVGs in Firefox.

**Comment by jacobwgillespie** [comment] 2018-11-30 00:54
I'm going to close this issue as I believe Styled Icons is functioning correctly - it just provides a bunch of SVGs after all - and the issue here is Firefox.  But feel free to post back in case anything comes up!

**Closed by jacobwgillespie** 2018-11-30 00:54 UTC
